Reset pulumi-java to v0.10.0 due to issue 1363 (#3342)
pulumi-java v0.11 introduced a change that causes this provider's
javadoc validation to fail.

```
> Task :javadoc
/home/runner/work/pulumi-azure-native/pulumi-azure-native/sdk/java/src/main/java/com/pulumi/azurenative/media/StreamingPolicy.java:258: error: unterminated inline tag
 * {@code
```

https://github.com/pulumi/pulumi-azure-native/actions/runs/9446393713/job/26018076202