Update `$ref` references in metadata when parameterizing (#4031)
This fixes an omission in #4010. Metadata contains `$ref`'s that need to
be updated when parameterizing because all the tokens change, like in
the schema.

This fixes this error I had brought up elsewhere:
> error: azure-native_storage_v20240101:storage/v20240101:StorageAccount
resource 'sa' has a problem: schema type
'azure-native:storage/v20240101:Sku' not found