Fix azure.IsNotFound for new azcore error type (#3842)
Fixes an issue I discovered today when trying to reproduce another issue
report. `pulumi refresh` is broken for this provider:
```
$ PATH="$HOME/pulumi/pan/bin:$PATH" pulumi refresh --skip-preview -s dev

     pulumi:pulumi:Stack                      recoveryservices-protecteditem-dev  **failed**                1 error; 4 warnings
 ~   ├─ azure-native:resources:ResourceGroup  resourceGroup                       **refreshing failed**     1 error

  azure-native:resources:ResourceGroup (resourceGroup):
    error: Code="ResourceGroupNotFound" Message="Resource group 'resourceGroup3f871416' could not be found."
```

The reason is that #3783 regressed `azure.IsNotFound`, causing `Read` to
report an error when a resource doesn't exist in Azure.

This PR fixes the problem and adds test coverage.