Handle non-JSON responses more gracefully (#3210)
In #3208 we see a case where an Azure API responds with a non-JSON body
in an error case. We don't expect that and run
`autorest.ByUnmarshallingJSON`, causing a confusing deserialization
error:
```
error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF
```

After this change, the same program errors with
```
error: unexpected response from the service: '', HTTP status 404 Not Found
```