Bump AKS K8s versions to supported ones (#3550)
Fixes a [master build failure](https://github.com/pulumi/pulumi-azure-native/actions/runs/10629197744)
blocking releases.

> azure-native:containerservice:ManagedCluster (cluster):
error: Code=“BadRequest” Message=“Managed cluster wn6m4dzn3fjw is on
version 1.27.9 which is not supported in this region. Please use [az aks
get-versions] command to get the supported version list in this region.
For more information, please check
https://aka.ms/supported-version-list”

[Green full acceptance test](https://github.com/pulumi/pulumi-azure-native/actions/runs/10634357333)