Improve auth CLI missing error (#3349)
Add context for why the CLI is expected and what operation is being
attempted.

Fixes https://github.com/pulumi/pulumi-azure-native/issues/3347

This will now print a message like:

```
Diagnostics:
  azure-native:features:SubscriptionFeatureRegistration (subscriptionFeatureRegistration):
    error: checking az cli version: could not find `az`: exec: "az": executable file not found in $PATH: MSI, OIDC, 
      client secret and client certificate authentication are not configured so we require the AZ CLI for authentication
```