Migrate servicebus-recreate test
Add `Additive: true` because otherwise the second step fails with:

  error: PULUMI_ACCESS_TOKEN must be set for login during non-interactive CLI sessions

Seems to be related to a historic regression: https://github.com/pulumi/pulumi/issues/12859